# Config file of Snakefile bam2vcf
# Load environment from within jonasl environment with $ conda activate bam2vcf

metadata: /media/labgenoma4/DATAPART7/duda_grupo/raw_data/genomes/genomes_metadata_2021APR10.tsv

ref:
    species: "Lynx canadensis"
    assembly: "mLynCan4.pri.v2"
    chromosome_tag: "CM"
    file: /media/labgenoma4/DATAPART7/duda_grupo/references/mLynCan4.pri.v2/GCA_007474595.2_mLynCan4.pri.v2_genomic.fna.gz

outgroup: "PumCon1.0"

input:
    bam: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/bam_mLynCan4.pri.v2 

output:
    vcf: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/vcf_mLynCan4.pri.v2

bin:
    variantqc: /media/labgenoma4/DATAPART4/jonasl/bin/DISCVRSeq/DISCVRSeq-1.3.9.jar

scripts:
    plot_plink_pca: /media/labgenoma4/DATAPART4/jonasl/scripts/plot_plink_pca.py

