# Config file of Snakefile bam2vcf
# Load environment from within jonasl environment with $ conda activate bam2vcf

metadata: /media/labgenoma4/DATAPART7/duda_grupo/raw_data/genomes/genomes_metadata_2023FEB22.tsv
exclude: ["Fch-1a"]

ref:
    species: "Felis catus"
    assembly: "felCat9"
    chromosome_tag: "NC"
    MT: "NC_001700.1"
    sex_chr: ["NC_018741.3"]
    file: /media/labgenoma4/DATAPART7/duda_grupo/references/felCat9/GCF_000181335.3_Felis_catus_9.0_genomic.fna.gz
    repeatmasker_out: /media/labgenoma4/DATAPART7/duda_grupo/references/felCat9/GCF_000181335.3_Felis_catus_9.0_rm.out.gz

outgroup: ["PumCon1.0", "LYNX9", "PBE_2350"]

input:
    bam: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/bam_felCat9 

output:
    vcf: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/vcf_felCat9

bin:
    variantqc: /media/labgenoma4/DATAPART4/jonasl/bin/DISCVRSeq/DISCVRSeq-1.3.9.jar

scripts:
    plot_plink_pca: /media/labgenoma4/DATAPART4/jonasl/scripts/plot_plink_pca.py

