# Config file of Snakefile fastq2bam
# Load environment from within jonasl environment with $ conda activate fastq2bam

metadata: /media/labgenoma4/DATAPART7/duda_grupo/raw_data/genomes/genomes_metadata_2021APR10.tsv
exclude: ["mLynCan4", "bLge-252"]

ref:
    species: "Leopardus geoffroyi"
    assembly: "Lge-1"
    chromosome_tag: "chr"
    file: /media/labgenoma4/DATAPART7/duda_grupo/references/Lge_Assembly_v1/Lge-1_final.fna.gz

output:
    bam: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/bam_Lge-1
    
# Uses Trimmomatic
trim:
    jar: /media/labgenoma4/DATAPART4/jonasl/bin/Trimmomatic-0.39/trimmomatic-0.39.jar
    libr: /media/labgenoma4/DATAPART4/jonasl/bin/Trimmomatic-0.39/adapters/TruSeq3-PE.fa
    avgqual: "20"

scripts:
    plot_bg_coverage: /media/labgenoma4/DATAPART4/jonasl/scripts/plot_bg_coverage.R
