# Config file of Snakefile diversity
# Load environment from within jonasl environment with $ conda activate diversity

metadata: /media/labgenoma4/DATAPART7/duda_grupo/raw_data/genomes/genomes_metadata_2023FEB22.tsv
exclude: ["Fch-1a"]

ref:
    species: "Leopardus geoffroyi"
    assembly: "Lge-1"
    file: /media/labgenoma4/DATAPART7/duda_grupo/references/Lge_Assembly_v1/Lge-1_final.fna.gz

input:
    fragments_dir: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/fasta_Lge-1/repeatmasked/100kb40/windows
    filenames: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/fasta_Lge-1/repeatmasked/100kb40/filenames_informative.txt
    bam_dir: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/bam_Lge-1
    auto: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/roh/autosomes.txt # This file needs to be manually created, in the format acceptable to ROHan and for use in MSMC2

angsd:
    rf: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/heterozygosity/autosomes.rf.txt # This file needs to be manually created in the format acceptable to ANGSD

rohan:
    rohan: /media/labgenoma4/DATAPART4/jonasl/bin/rohan/src/rohan
    rohmu: 2e-4

seqbility_dir: /media/labgenoma4/DATAPART4/jonasl/bin/seqbility-20091110

msmc2: /media/labgenoma4/DATAPART4/jonasl/bin/msmc2/build/release/msmc2

output:
    fragments_dir: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/repeatmasked/5kb40
    heterozygosity: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/heterozygosity
    roh: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/roh
    demography: /media/labgenoma4/DATAPART4/jonasl/data/leopardus_phylogeny/diversity_Lge-1/demography

scripts:
    pairwise_pi: /media/labgenoma4/DATAPART4/jonasl/scripts/pairwise_pi.py
    pairwise_pi_plot: /media/labgenoma4/DATAPART4/jonasl/scripts/pairwise_pi_plot.py
    getHetvalues_folded: /media/labgenoma4/DATAPART4/jonasl/scripts/getHetvalues_folded.py
    bamCaller: /media/labgenoma4/DATAPART4/jonasl/bin/msmc-tools/bamCaller.py
    snpable: /media/labgenoma4/DATAPART4/jonasl/scripts/snpable.sh
    multihetsep: /media/labgenoma4/DATAPART4/jonasl/bin/msmc-tools/generate_multihetsep.py
    multihetsep_bs: /media/labgenoma4/DATAPART4/jonasl/bin/msmc-tools/multihetsep_bootstrap.py
    msmc2_plot: /media/labgenoma4/DATAPART4/jonasl/scripts/msmc2_plot_bs.py
    msmc2_consensus: /media/labgenoma4/DATAPART4/jonasl/scripts/msmc2_consensus.py
